name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  release:
    types: [created]

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
          cache: maven

      # Étape pour enlever "-SNAPSHOT" dans le pom.xml
      - name: Remove -SNAPSHOT from pom.xml
        run: mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      # Construction Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # On récupère le vrai nom du .jar (ex: discordbot-1.2.3.jar)
      - name: Find built jar name
        id: find_jar
        shell: bash
        run: echo "jar_name=$(basename $(ls target/discordbot-*.jar))" >> $GITHUB_OUTPUT

      # Upload du .jar sur la release (uniquement si release.created)
      - name: Upload JAR to release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/${{ steps.find_jar.outputs.jar_name }}
          asset_name: ${{ steps.find_jar.outputs.jar_name }}
          asset_content_type: application/java-archive

      # Génération des tags Docker (optionnel)
      - name: Docker metadata
        id: docker_meta
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # Connexion à GHCR
      - name: Login to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push de l'image Docker
      - name: Build and push Docker image
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      # Déploiement de l'image Docker (optionnel)
      - name: Deploy
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        uses: joelwmale/webhook-action@2.4.1
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
