name: Release Build

on:
  release:
    types: [created]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
          cache: maven

      # Étape pour enlever "-SNAPSHOT" dans le pom.xml
      - name: Remove -SNAPSHOT from pom.xml
        run: mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      # Construction Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # On récupère le vrai nom du .jar (ex: discordbot-1.2.3.jar)
      - name: Find built jar name
        id: find_jar
        shell: bash
        run: echo "jar_name=$(basename $(ls target/discordbot-*.jar))" >> $GITHUB_OUTPUT

      # Upload du .jar sur la release
      - name: Upload JAR to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/${{ steps.find_jar.outputs.jar_name }}
          asset_name: ${{ steps.find_jar.outputs.jar_name }}
          asset_content_type: application/java-archive
